"""init

Revision ID: 20eef3d2d398
Revises: 
Create Date: 2024-06-28 21:30:06.212661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20eef3d2d398'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('time_create', sa.TIMESTAMP(), nullable=True),
    sa.Column('time_update', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buy_sell_ratio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_symbol', sa.Integer(), nullable=True),
    sa.Column('buy_volume', sa.Float(), nullable=True),
    sa.Column('sell_volume', sa.Float(), nullable=True),
    sa.Column('ratio', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('time_create', sa.TIMESTAMP(), nullable=True),
    sa.Column('time_update', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_symbol'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buy_sell_ratio_id_symbol'), 'buy_sell_ratio', ['id_symbol'], unique=False)
    op.create_index(op.f('ix_buy_sell_ratio_timestamp'), 'buy_sell_ratio', ['timestamp'], unique=False)
    op.create_table('kline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_symbol', sa.Integer(), nullable=True),
    sa.Column('open', sa.Double(), nullable=True),
    sa.Column('high', sa.Double(), nullable=True),
    sa.Column('low', sa.Double(), nullable=True),
    sa.Column('close', sa.Double(), nullable=True),
    sa.Column('volume', sa.Double(), nullable=True),
    sa.Column('number_of_trades', sa.Integer(), nullable=True),
    sa.Column('time_open', sa.TIMESTAMP(), nullable=True),
    sa.Column('time_close', sa.TIMESTAMP(), nullable=True),
    sa.Column('time_create', sa.TIMESTAMP(), nullable=True),
    sa.Column('time_update', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_symbol'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kline_id_symbol'), 'kline', ['id_symbol'], unique=False)
    op.create_index(op.f('ix_kline_time_close'), 'kline', ['time_close'], unique=False)
    op.create_table('open_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_symbol', sa.Integer(), nullable=True),
    sa.Column('interest', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('time_create', sa.TIMESTAMP(), nullable=True),
    sa.Column('time_update', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_symbol'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_open_interest_id_symbol'), 'open_interest', ['id_symbol'], unique=False)
    op.create_index(op.f('ix_open_interest_timestamp'), 'open_interest', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_open_interest_timestamp'), table_name='open_interest')
    op.drop_index(op.f('ix_open_interest_id_symbol'), table_name='open_interest')
    op.drop_table('open_interest')
    op.drop_index(op.f('ix_kline_time_close'), table_name='kline')
    op.drop_index(op.f('ix_kline_id_symbol'), table_name='kline')
    op.drop_table('kline')
    op.drop_index(op.f('ix_buy_sell_ratio_timestamp'), table_name='buy_sell_ratio')
    op.drop_index(op.f('ix_buy_sell_ratio_id_symbol'), table_name='buy_sell_ratio')
    op.drop_table('buy_sell_ratio')
    op.drop_table('symbol')
    # ### end Alembic commands ###
