"""drop buy_sell_ratio

Revision ID: 8e04c68a9cfe
Revises: 3bcdbdb9b39d
Create Date: 2024-06-30 12:45:17.100426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e04c68a9cfe'
down_revision: Union[str, None] = '3bcdbdb9b39d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_buy_sell_ratio_id_symbol', table_name='buy_sell_ratio')
    op.drop_index('ix_buy_sell_ratio_timestamp', table_name='buy_sell_ratio')
    op.drop_table('buy_sell_ratio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buy_sell_ratio',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_symbol', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('buy_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sell_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('time_create', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('time_update', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_symbol'], ['symbol.id'], name='buy_sell_ratio_id_symbol_fkey'),
    sa.PrimaryKeyConstraint('id', name='buy_sell_ratio_pkey')
    )
    op.create_index('ix_buy_sell_ratio_timestamp', 'buy_sell_ratio', ['timestamp'], unique=False)
    op.create_index('ix_buy_sell_ratio_id_symbol', 'buy_sell_ratio', ['id_symbol'], unique=False)
    # ### end Alembic commands ###
